CodingChallenge/Models/People.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web.Script.Serialization;

namespace CodingChallenge.Models
{
    public class People
    {
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public List<Pet> Pets { get; set; }


        internal static List<People> GetAllPeopleWithPets()
        {
            List<People> output = null;
            try
            {
                using (var client = new WebClient())
                {
                    var uri = new Uri(ConfigurationManager.AppSettings["JsonService.URL"]);
                    client.Headers[HttpRequestHeader.ContentType] = "application/json";
                    string json = client.DownloadString(uri);
                    output = (new JavaScriptSerializer()).Deserialize<List<People>>(json);
                }
            }
            catch (Exception ex)
            {
                //handle exception via email or file
            }
            return output;
        }

        internal static PetsViewModel GetOrderedPetsWithOwnersGender()
        {
            var viewModel = new PetsViewModel();
            try
            {
                List<People> people = GetAllPeopleWithPets();
                IEnumerable<dynamic> petsList = people
                    .Where(a => a.Pets != null)
                            .SelectMany(a => a.Pets.Where(b => b.Type.Equals("Cat"))
                                        .Select(b =>
                                       new
                                       {
                                           OwnerGender = a.Gender,
                                           PetName = b.Name
                                       }
                                       ))
                            .OrderBy(b => b.PetName)
                            .Distinct()
                            .GroupBy(c => c.OwnerGender)
                            .Select(a => new
                                {
                                    Key = a.Key,
                                    Items = a
                                })
                            .ToList();
                viewModel.PetsList = petsList;
            }
            catch (Exception ex)
            {
                //handle exception via email or file
            }
            return viewModel;
        }
    }
}

CodingChallenge/Models/Pets.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CodingChallenge.Models
{
    public class Pet
    {
        public string Name { get; set; }
        public string Type { get; set; }
    }
}

CodingChallenge/Models/PetsViewModel.cs
using System.Collections.Generic;

namespace CodingChallenge.Models
{
    public class PetsViewModel
    {
        public IEnumerable<dynamic> PetsList { get; set; }
    }
}

CodingChallenge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodingChallenge.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CodingChallenge/Controllers/PeopleController.cs
using CodingChallenge.Models;
using System.Web.Mvc;

namespace CodingChallenge.Controllers
{
    public class PeopleController : Controller
    {
        // GET: People
        public ActionResult Index()
        {
            var model = People.GetOrderedPeopleWithPets();
            return View(model);
        }
    }
}

CodingChallenge/Controllers/PetsController.cs
using CodingChallenge.Models;
using System.Web.Mvc;

namespace CodingChallenge.Controllers
{
    public class PetsController : Controller
    {
        // GET: People
        public ActionResult Index()
        {
            var model = People.GetOrderedPetsWithOwnersGender();
            return View(model);
        }
    }
}

CodingChallenge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Coding Challenge</h1>
    <p class="lead">By Keshab Pandey</p>
    <p>
    <a href="@Url.Action("Index", "Pets")" class="btn btn-primary btn-lg">View all pets with owner's gender &raquo;</a></p>
</div>

CodingChallenge/Views/Pets/Index.cshtml
@using CodingChallenge.Models;
@model PetsViewModel
@{
    ViewBag.Title = "Results";
}

<h2>Results:</h2>

<div>
    @foreach (var group in Model.PetsList)
    {
        @Html.Encode(group.GetType().GetProperty("Key").GetValue(group, null))
        <ul>
            @foreach (var item in group.GetType().GetProperty("Items").GetValue(group, null))
            {
                <li>@item.GetType().GetProperty("PetName").GetValue(item, null)</li>
            }
        </ul>
    }
</div>

CodingChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Coding Challenge</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Coding Challenge", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pets", "Index", "Pets")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Keshab Pandey</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>